name: meet_demo
description: "An online meeting application created using Jitsy Library."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ## added
  provider: ^6.1.2
  connectivity_plus: ^6.0.5
  jitsi_meet_flutter_sdk: ^10.2.1
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  http: ^1.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.0.2
  awesome_notifications: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env